force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Point_Ledger__c/Point_Ledger__c.object-meta.xml
<CustomObject>
    <label>Point Ledger</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Point Ledger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Point_Ledger__c/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Point Ledgers (Loyalty Profile)</relationshipLabel>
    <relationshipName>Point_Ledgers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RewardPointsService.cls
public with sharing class RewardPointsService {
    
    @AuraEnabled(cacheable=true)
    public static MyPointsWrapper getCurrentUserRewardPointsData() {
        User currentUser = UserSelector.getUserById(UserInfo.getUserId());
        Loyalty_Profile__c loyaltyProfile = LoyaltyProfileSelector.getLoyaltyProfileByContactId(currentUser.ContactId);
        MyPointsWrapper wrapper = new MyPointsWrapper();
        wrapper.expiringPoints = getLatestExpiringPoints(loyaltyProfile);
        wrapper.loyaltyProfile = loyaltyProfile;
        return wrapper;
    }

    @AuraEnabled(cacheable=true)
    public static List<Loyalty_Profile__c> getLeaderboard() {
        List<Loyalty_Profile__c> loyaltyProfiles = LoyaltyProfileSelector.getTopProfilesByRewarPoints(5);
        return loyaltyProfiles;
    }

    @AuraEnabled(cacheable=true)
    public static List<Point_Ledger__c> getRedemptionHistory() {
        User currentUser = UserSelector.getUserById(UserInfo.getUserId());
        Loyalty_Profile__c loyaltyProfile = LoyaltyProfileSelector.getLoyaltyProfileByContactId(currentUser.ContactId);
        List<Point_Ledger__c> pointLedger = PointLedgerSelector.getPointLedgerByLoyaltyProfileId(loyaltyProfile.Id);
        return pointLedger;
    }

    private static Point_Ledger__c getLatestExpiringPoints(Loyalty_Profile__c loyaltyProfile) {
        Point_Ledger__c pointLedger = PointLedgerSelector.getLatestExpiringPointLedger(loyaltyProfile.Id);
        return pointLedger;
    }

    public class MyPointsWrapper {
        @AuraEnabled
        public Loyalty_Profile__c loyaltyProfile {get; set;}
        @AuraEnabled
        public Point_Ledger__c expiringPoints {get; set;}
    }
}