force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Profile__c/fields/Available_Points__c.field-meta.xml
<CustomField>
    <fullName>Available_Points__c</fullName>
    <description>Total points available on the user.</description>
    <formula>Total_Points_Accrued__c -  Total_Points_Redeemed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loyalty_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Related contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Profiles</relationshipLabel>
    <relationshipName>Loyalty_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Profile__c/fields/Referral_Code__c.field-meta.xml
<CustomField>
    <fullName>Referral_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Referral code of the user that can be used to refer other users.</description>
    <label>Referral Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loyalty_Profile__c/fields/Reward_Points_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points_Expiry_Date__c</fullName>
    <description>Expiry date of the user&apos;s reward points that were accrued the latest.</description>
    <label>Latest Reward Points Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loyalty_Profile__c/fields/Was_Referral_Popup_Displayed__c.field-meta.xml
<CustomField>
    <fullName>Was_Referral_Popup_Displayed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To show Referral Pop Up only once when user logs in to the portal</description>
    <label>Was Referral Popup Displayed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LoyaltyProfileSelector.cls
public inherited sharing class LoyaltyProfileSelector {
   public static Loyalty_Profile__c getLoyaltyProfileByContactId(
     String contactId
   ) {
     return [
         SELECT
            Id,
            Name,
            Contact__c,
            Available_Points__c,
            Reward_Points_Expiry_Date__c,
            Was_Referral_Popup_Displayed__c
         FROM
            Loyalty_Profile__c
         WHERE
            Contact__c = :contactId
         LIMIT 1
     ];
   }

   public static List<Loyalty_Profile__c> getLoyaltyProfilesByIds(
     Set<Id> loyaltyProfileIds
   ) {
     return [
         SELECT
            Id,
            Reward_Points_Expiry_Date__c,
            Contact__c
         FROM
            Loyalty_Profile__c
         WHERE
            Id IN :loyaltyProfileIds
     ];
   }

   public static List<Loyalty_Profile__c> getTopProfilesByRewarPoints(
     Integer recordLimit
   ) {
     return [
         SELECT
            Id,
            Name,
            Contact__c,
            Contact__r.Name,
            Available_Points__c
         FROM
            Loyalty_Profile__c
         ORDER BY
            Available_Points__c DESC
         LIMIT :recordLimit
     ];
   }

   public static Loyalty_Profile__c getLoyaltyProfileByReferralCode(
     String referralCode
   ) {
     return [
      SELECT 
         Id, 
         Referral_Code__c 
      FROM 
         Loyalty_Profile__c 
      WHERE 
         Referral_Code__c = :referralCode
      LIMIT 1
     ];
   }

 }