force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Related contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Profiles</relationshipLabel>
    <relationshipName>Loyalty_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Profile__c/fields/Reward_Points_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_Points_Expiry_Date__c</fullName>
    <description>Expiry date of the user&apos;s reward points that were accrued the latest.</description>
    <label>Latest Reward Points Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/Point_Ledger__c.object-meta.xml
<CustomObject>
    <label>Point Ledger</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Point Ledger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Point_Ledger__c/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Point Ledgers (Loyalty Profile)</relationshipLabel>
    <relationshipName>Point_Ledgers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source of the points accrued/redeemed.</description>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accrual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PointLedgerTriggerHandler.cls
public without sharing class PointLedgerTriggerHandler {

    private static final List<String> emailTemplateNames = new List<String> {
        System.Label.Order_Reward_Points_Credit_Email_Template,
        System.Label.Review_Submitted_Email_Template,
        System.Label.Successful_Referral_Email_Template
    };

    private static final Map<String, String> POINT_SOURCE_TO_EMAIL_TEMPLATE_MAP = new Map<String, String> {
        'Order' => System.Label.Order_Reward_Points_Credit_Email_Template,
        'Review' => System.Label.Review_Submitted_Email_Template,
        'Referral' => System.Label.Successful_Referral_Email_Template
    };
    
    public void onAfterInsert(List<Point_Ledger__c> newPointLedgers, Map<Id, Point_Ledger__c> newPointLedgersMap) {
        updatePointExpiryDateOnLoyaltyProfile(newPointLedgers);
        sendEmailNotification(newPointLedgers);
    }

    private static void updatePointExpiryDateOnLoyaltyProfile(List<Point_Ledger__c> newPointLedgers) {
        Set<Id> loyaltyProfileIds = new Set<Id>();
        for (Point_Ledger__c pointLedger : newPointLedgers) {
            if(pointLedger.Transaction_Type__c == 'Accrual') {
                loyaltyProfileIds.add(pointLedger.Loyalty_Profile__c);
            }
        }

        List<Loyalty_Profile__c> loyaltyProfiles = new List<Loyalty_Profile__c>();
        try {
            loyaltyProfiles = LoyaltyProfileSelector.getLoyaltyProfilesByIds(loyaltyProfileIds);
        } catch(QueryException e) {
            System.debug('Error: ' + e.getMessage());
        }


        for (Loyalty_Profile__c loyaltyProfile : loyaltyProfiles) {
            loyaltyProfile.Reward_Points_Expiry_Date__c = Date.today().addMonths(6);
        }

        try {
            if(!loyaltyProfiles.isEmpty()) {
                Database.update(loyaltyProfiles);
            }
        } catch(DmlException e) {
            System.debug('Error: ' + e.getMessage());
        }
    }

    public static void sendEmailNotification(List<Point_Ledger__c> newPointLedgers) {
        Map<Id, String> loyaltyProfileIdToPointSourceMap = new Map<Id, String>();
        Map<Id, String> contactIdToPointSourceMap = new Map<Id, String>();
        Map<String, Id> sourceToEmailTemplateMap = new Map<String, Id>();
        for(Point_Ledger__c pointLedger : newPointLedgers) {
            if(pointLedger.Transaction_Type__c == 'Accrual') {
                loyaltyProfileIdToPointSourceMap.put(pointLedger.Loyalty_Profile__c, pointLedger.Source__c);
            }
        }

        List<Loyalty_Profile__c> loyaltyProfiles = LoyaltyProfileSelector.getLoyaltyProfilesByIds(loyaltyProfileIdToPointSourceMap.keySet());
        for(Loyalty_Profile__c loyaltyProfile : loyaltyProfiles) {
            contactIdToPointSourceMap.put(loyaltyProfile.Contact__c, loyaltyProfileIdToPointSourceMap.get(loyaltyProfile.Id));
        }

        for(EmailTemplate template : EmailTemplateSelector.getEmailTemplatesByNames(emailTemplateNames)) {
            sourceToEmailTemplateMap.put(template.Name, template.Id);
        }

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(String contactId : contactIdToPointSourceMap.keySet()) {
            String source = contactIdToPointSourceMap.get(contactId);
            String emailTemplateName = POINT_SOURCE_TO_EMAIL_TEMPLATE_MAP.get(source);
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setTemplateId(sourceToEmailTemplateMap.get(emailTemplateName));
            email.setTargetObjectId(contactId); // Sending emails to contacts doesn't consume the daily Single Email Message limit
            email.setSaveAsActivity(false);
            emails.add(email);
        }

        try {
            if(!emails.isEmpty()) {
                Messaging.sendEmail(emails);
            }
        } catch (EmailException e) {
            System.debug('Error: ' + e.getMessage());
        }
    }
}