force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/Point_Ledger__c.object-meta.xml
<CustomObject>
    <label>Point Ledger</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Point Ledger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Point_Ledger__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>Expiry date of the reward point. Reward points expire after 6 months from when they were accrued.</description>
    <formula>IF(ISPICKVAL(Transaction_Type__c, &apos;Accrual&apos;), ADDMONTHS(CreatedDate,  VALUE($Label.Point_Expiration_Duration_In_Months)), null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Point Ledgers (Loyalty Profile)</relationshipLabel>
    <relationshipName>Point_Ledgers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accrual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PointLedgerSelector.cls
public inherited sharing class PointLedgerSelector {
    public static List<Point_Ledger__c> getPointLedgerByLoyaltyProfileId(String loyaltyProfileId) {
        return [
            SELECT
                Id,
                Transaction_Type__c,
                CreatedDate,
                Total_Points__c
            FROM
                Point_Ledger__c
            WHERE
                Loyalty_Profile__c = :loyaltyProfileId
            AND
                Transaction_Type__c = 'Redemption'
            AND 
                Total_Points__c > 0
            ORDER BY
                CreatedDate
            DESC 
        ];
    }

    public static Point_Ledger__c getLatestExpiringPointLedger(String loyaltyProfileId) {
        return [
            SELECT
                Id,
                Total_Points__c,
                Expiry_Date__c
            FROM
                Point_Ledger__c
            WHERE
                Expiry_Date__c > Today
            AND
                Transaction_Type__c = 'Accrual'
            AND
                Loyalty_Profile__c = :loyaltyProfileId
            ORDER BY
                Expiry_Date__c ASC
            LIMIT 1
        ] ?? null;
    }
}