force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Profile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Related contact.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loyalty Profiles</relationshipLabel>
    <relationshipName>Loyalty_Profiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loyalty_Profile__c/fields/Referral_Code__c.field-meta.xml
<CustomField>
    <fullName>Referral_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Referral code of the user that can be used to refer other users.</description>
    <label>Referral Code</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/InsertLoyaltyProfilesBatch.cls
/**
 * batch to create Loyalty Profile records for existing community contacts whose loyalty profile records don't exist.
 */

public without sharing class InsertLoyaltyProfilesBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator([SELECT Id FROM Contact WHERE Id NOT IN (SELECT Contact__c FROM Loyalty_Profile__c)]);
    }

    public void execute(Database.BatchableContext context, List<Contact> scope) {
        List<Loyalty_Profile__c> loyaltyProfiles = new List<Loyalty_Profile__c>();
        Set<Id> contactIds = new Set<Id>();
        Map<Id, User> contactIdToUserMap = new Map<Id, User>();
        for(Contact contactRecord : scope) {
            contactIds.add(contactRecord.Id);
        }

        for(User relatedUser : UserSelector.getCommunityUsersByContactIds(contactIds)) {
            contactIdToUserMap.put(relatedUser.ContactId, relatedUser);
        }

        for (Contact contact : scope) {
            if(!contactIdToUserMap.containsKey(contact.Id)) {
                continue;
            }
            Loyalty_Profile__c loyaltyProfile = new Loyalty_Profile__c();
            loyaltyProfile.Contact__c = contact.Id;
            loyaltyProfile.Referral_Code__c = CustomerLoyaltyProgramUtil.generateReferralCode();
            loyaltyProfiles.add(loyaltyProfile);
        }

        if (!loyaltyProfiles.isEmpty()) {
            try {
                Database.insert(loyaltyProfiles, false);
            } catch (Exception e) {
                System.debug('Error inserting Loyalty Profiles: ' + e.getMessage());
                // Use logger mechanism to log these errors - Nebula Logger, etc.
                // Didn't implement because of time constraints.
            }
        }
    }

    public void finish(Database.BatchableContext context) {
        System.debug('Batch job finished.');
        // Send an email notification to the admin if needed
        // Also can use Database.SaveResult to log records that failed to insert
        // Didn't implement because of time constraints.
    }
}