force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Points_Redeemed__c.field-meta.xml
<CustomField>
    <fullName>Points_Redeemed__c</fullName>
    <description>Stores the points redeemed while checkout.</description>
    <label>Points Redeemed</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/Point_Ledger__c.object-meta.xml
<CustomObject>
    <label>Point Ledger</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Point Ledger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Point_Ledger__c/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Point Ledgers (Loyalty Profile)</relationshipLabel>
    <relationshipName>Point_Ledgers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source of the points accrued/redeemed.</description>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accrual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerHandler.cls
public without sharing class OrderTriggerHandler {
    public void onAfterInsert(List<Order> newOrders) {
        createPointLedgerRecords(newOrders);
    }

    public static void createPointLedgerRecords(List<Order> newOrders) {
        List<Point_Ledger__c> pointLedgerRecords = new List<Point_Ledger__c>();
        for(Order order : newOrders) {
            if(order.Points_Redeemed__c > 0) {
                Point_Ledger__c pointLedgerRecord = new Point_Ledger__c();
                pointLedgerRecord.Loyalty_Profile__c = order.Loyalty_Profile__c;
                pointLedgerRecord.Source__c = 'Order';
                pointLedgerRecord.Total_Points__c = order.Points_Redeemed__c;
                pointLedgerRecord.Transaction_Type__c = 'Redemption';
                pointLedgerRecords.add(pointLedgerRecord);
            }
            Point_Ledger__c pointLedgerRecord = new Point_Ledger__c();
            pointLedgerRecord.Loyalty_Profile__c = order.Loyalty_Profile__c;
            pointLedgerRecord.Source__c = 'Order';
            pointLedgerRecord.Total_Points__c = Decimal.valueOf(System.Label.Points_Accrual_Factor) * order.TotalAmount;
            pointLedgerRecord.Transaction_Type__c = 'Accrual';
            pointLedgerRecords.add(pointLedgerRecord);
        }

        try {
            Database.insert(pointLedgerRecords);
        } catch(DmlException e) {
            System.debug('An unexpected error has occurred: ' + e.getMessage());
            //Use Logger mechanism to log the error
        }
    }
}