force-app/main/default/objects/Loyalty_Profile__c/Loyalty_Profile__c.object-meta.xml
<CustomObject>
    <description>Stores profiles of the ecommerce users.</description>
    <label>Loyalty Profile</label>
    <nameField>
        <label>Loyalty Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loyalty Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loyalty_Profile__c/fields/Available_Points__c.field-meta.xml
<CustomField>
    <fullName>Available_Points__c</fullName>
    <description>Total points available on the user.</description>
    <formula>Total_Points_Accrued__c -  Total_Points_Redeemed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Voucher__c.field-meta.xml
<CustomField>
    <fullName>Voucher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voucher</label>
    <referenceTo>Voucher__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/Point_Ledger__c.object-meta.xml
<CustomObject>
    <label>Point Ledger</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Point Ledger</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Point Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Point_Ledger__c/fields/Loyalty_Profile__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Profile__c</fullName>
    <description>Related loyalty profile.</description>
    <label>Loyalty Profile</label>
    <referenceTo>Loyalty_Profile__c</referenceTo>
    <relationshipLabel>Point Ledgers (Loyalty Profile)</relationshipLabel>
    <relationshipName>Point_Ledgers1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source of the points accrued/redeemed.</description>
    <label>Source</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Point_Ledger__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accrual</fullName>
            </value>
            <value>
                <fullName>Redemption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <description>Stores the vouchers available.</description>
    <label>Voucher/Deal</label>
    <nameField>
        <displayFormat>VD-{0000}</displayFormat>
        <label>Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vouchers/Deals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the voucher active?</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>stores the voucher code.</description>
    <label>Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Available discount.</description>
    <label>Discount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Absolute</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckoutController.cls
public with sharing class CheckoutController {
    @AuraEnabled(cacheable=true)
    public static Product2 getProductDetails(String productId) {
        return [
            SELECT Id, Name, Description, DisplayUrl,
                   (SELECT UnitPrice FROM PricebookEntries WHERE IsActive = TRUE LIMIT 1)
            FROM Product2
            WHERE Id = :productId
        ];
    }

    @AuraEnabled
    public static Decimal applyVoucherCode(String voucherCode) {
        List<Voucher__c> voucherList = [SELECT Code__c,Discount__c,Discount_Type__c
        FROM Voucher__c 
        WHERE Code__c = :voucherCode AND Active__c = true LIMIT 1];
        if (!voucherList.isEmpty()) {
            return voucherList[0].Discount__c;
        } else {
            throw new AuraHandledException('Invalid voucher code.');
        }
    }

    @AuraEnabled(cacheable=true)
    public static Decimal getLoyaltyPoints() {
        // Fetch the user's loyalty points from the LoyaltyProfile__c object
        User currentUser = UserSelector.getUserById(UserInfo.getUserId());
    List<Loyalty_Profile__c> profiles = new List<Loyalty_Profile__c>{LoyaltyProfileSelector.getLoyaltyProfileByContactId(currentUser.ContactId)};
    /*
    List<Loyalty_Profile__c> profiles = [
            SELECT Available_Points__c FROM Loyalty_Profile__c WHERE OwnerId = :UserInfo.getUserId() LIMIT 1
        ];
        */
        if (profiles.isEmpty()) {
            return 0;
        }

        return profiles[0].Available_Points__c;
    }

    @AuraEnabled
public static Id createOrder(Map<String, Object> orderData) {
    String productId = (String) orderData.get('productId');
    List<PricebookEntry> pricebookEntries = [
        SELECT Id ,Pricebook2Id
        FROM PricebookEntry 
        WHERE Product2Id = :productId AND IsActive = TRUE 
        LIMIT 1
    ];

    if (pricebookEntries.isEmpty()) {
        throw new AuraHandledException('No active PricebookEntry found for the selected product.');
    }

    Id pricebookEntryId = pricebookEntries[0].Id;

    User currentUser = UserSelector.getUserById(UserInfo.getUserId());
    Loyalty_Profile__c profile = LoyaltyProfileSelector.getLoyaltyProfileByContactId(currentUser.ContactId);
    
    String voucherCode = (String) orderData.get('voucherCode');
    List<Voucher__c> voucherList = [SELECT Code__c,Discount__c,Discount_Type__c
        FROM Voucher__c 
        WHERE Code__c = :voucherCode AND Active__c = true LIMIT 1];

    // Create Order
    Order order = new Order(
        AccountId = '001dM00002FjVMIQA3',//UserInfo.getUserId(), 
        EffectiveDate = Date.today(),
        Status = 'Draft',
        BillingStreet = (String)orderData.get('deliveryAddress'),
        Pricebook2Id = pricebookEntries[0].Pricebook2Id, // Associate the Pricebook
        Loyalty_Profile__c = profile.Id,
        Voucher__c = !voucherList.isEmpty() ? voucherList[0].Id : null
    );
    insert order;

    // Create OrderItem
    OrderItem item = new OrderItem(
        OrderId = order.Id,
        PricebookEntryId = pricebookEntryId,
        Quantity = 1,
        Product2id = productId,
        UnitPrice = (Decimal)orderData.get('price')
        //ListPrice = (Decimal)orderData.get('price')
    );
    insert item;

    List<Point_Ledger__c> ledgerList = new List<Point_Ledger__c>();
    Decimal redeemedPoints = 0;
    if(orderData.get('redeemedPoints') != null) {
        redeemedPoints = Decimal.valueOf((String)orderData.get('redeemedPoints'));
    }
    Decimal price = (Decimal)orderData.get('price');
    if (redeemedPoints > 0) {
        /*
        Loyalty_Profile__c profile = [
            SELECT Available_Points__c FROM Loyalty_Profile__c WHERE OwnerId = :UserInfo.getUserId() LIMIT 1
        ];
        */
        Point_Ledger__c redemptionLedger = new Point_Ledger__c(
            Loyalty_Profile__c = profile.Id,
            Total_Points__c = redeemedPoints,//(Decimal)orderData.get('redeemedPoints'),
            Transaction_Type__c = 'Redemption',
            Source__c = 'Order'
        );
        ledgerList.add(redemptionLedger);
        //insert ledger;
    } 

    Decimal accrualFactor = Decimal.valueOf(System.Label.Points_Accrual_Factor);

    Point_Ledger__c accrualLedger = new Point_Ledger__c(
            Loyalty_Profile__c = profile.Id,
            Total_Points__c = Integer.valueOf(price*accrualFactor),//(Decimal)orderData.get('redeemedPoints'),
            Transaction_Type__c = 'Accrual',
            Source__c = 'Order'
        );
        ledgerList.add(accrualLedger);

    if (ledgerList.size() > 0) {
        insert ledgerList;
    }

    return order.Id;
}
}